=== NibbleTech/es-rad-app-generator/demo/demo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="esRadApp" type="esRadAppType"/>
  <xs:complexType name="propertyMapType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="eventProperty" use="required"/>
        <xs:attribute type="xs:string" name="entityProperty" use="required"/>
        <xs:attribute type="xs:string" name="eventPropertyType"/>
        <xs:attribute type="xs:string" name="entityPropertyType"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="propertyMappingsType">
    <xs:sequence>
      <xs:element type="propertyMapType" name="propertyMap" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="createType">
    <xs:sequence>
      <xs:element type="propertyMappingsType" name="propertyMappings"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="entity" use="required"/>
  </xs:complexType>
  <xs:complexType name="sideEffectsType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element type="createType" name="create" minOccurs="0"/>
      <xs:element type="updateType" name="update" minOccurs="0"/>
      <xs:element type="deleteType" name="delete" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="whenType">
    <xs:sequence>
      <xs:element type="sideEffectsType" name="sideEffects"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="description" use="required"/>
    <xs:attribute type="xs:string" name="eventName" use="required"/>
  </xs:complexType>
  <xs:complexType name="updateType">
    <xs:sequence>
      <xs:element type="propertyMappingsType" name="propertyMappings"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="entity" use="required"/>
  </xs:complexType>
  <xs:complexType name="deleteType">
    <xs:sequence>
      <xs:element type="propertyMappingsType" name="propertyMappings"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="entity" use="required"/>
  </xs:complexType>
  <xs:complexType name="eventConsumerType">
    <xs:sequence>
      <xs:element type="whenType" name="when" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="esRadAppType">
    <xs:sequence>
      <xs:element type="eventsType" name="events"/>
      <xs:element type="eventConsumerType" name="eventConsumers"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="eventsType">
    <xs:sequence>
      <xs:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="eventType">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="appliesTo" use="required"/>
  </xs:complexType>
</xs:schema>

=== NibbleTech/es-rad-app-generator/demo/esradapp.xml
<?xml version="1.0" encoding="UTF-8"?>
<esRadApp
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="demo.xsd"
>
    <events>
        <when description="Thing is sent" eventName="ThingSent">
            <sideEffects>
                <create entity="Thing">
                    <propertyMappings>
                        <propertyMap eventProperty="createEventProp1" entityProperty="createEntityProp1"/>
                        <propertyMap eventProperty="createEventProp2"
                                     eventPropertyType="int"
                                     entityProperty="createEntityProp2"
                                     entityPropertyType="int"
                        />
                    </propertyMappings>
                </create>
            </sideEffects>
        </when>
        <when description="Thing is updated" eventName="ThingUpdated">
            <sideEffects>
                <update entity="Thing">
                    <propertyMappings>
                        <propertyMap eventProperty="updateEventProp1"
                                     eventPropertyType="string"
                                     entityProperty="updateEntityProp1"
                                     entityPropertyType="string"/>
                    </propertyMappings>
                </update>
            </sideEffects>
        </when>
        <when description="Thing is deleted" eventName="ThingDeleted">
            <sideEffects>
                <delete entity="Thing">
                    <propertyMappings>
                        <propertyMap eventProperty="deleteEventProp1" entityProperty="deleteEntityProp1"/>
                    </propertyMappings>
                </delete>
            </sideEffects>
        </when>
    </events>
</esRadApp>
